### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by StarSovu** [rpulkka/MST-Comparison#1]
Projekti ladattu 14.2.2019 22:40

### Ohjelman rakenne
Ohjelma vaikuttaa toteuttavan tehtävän oikein hyvin. Pakkausrakenne on jaoteltu selkeästi, algoritmiluokat yhdessä ja muut toiminnot jokainen omassa pakkauksessaan. Ymmärrsin koodia tutkimalla helposti sen mitä ohjelmassa tapahtuu.

### Käytettävyys

Oletan että nopeudet ovat millisekunteja, sen voisi varmuuden vuoksi mainita tulosteessa. Algoritmejä on sen verran vähän että ei välttämättä tarvitse luetella erikseen mikä oli nopein ja mikä hitain.

### Testit

Ajaessani testit kahdeksan testiä kymmenestä ei toiminut vaan antoivat virheilmoituksen.

**Comment by rpulkka** [comment]
Kiitos palautteesta!

Testitiedostojen lukeminen JUNIT testeissä oli tuolloin tosiaan vielä työn alla, nyt JUNIT on laitettu lukemaan testitiedostojani. 39 testistä kuinkin suoriutuu tällä erää vain 26, sillä Primin algoritmia uusitaan tällä erää ja se on siksi toistaiseksi toimintakelvoton. Tilanne korjautuu ensi viikolla. 

Tsemppiä kurssin loppuun!
