### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by jjjjm** [rpulkka/MST-Comparison#2]
Testit näyttävät toimivan ja näyttäsivät testaavan ihan konkreettisia asioita. Projekti muutenkin kokonaisuudessan näyttää ihan hyvältä ja varsinkin kansio rakenteet ovat mukavan siistejä. Ohjelma myös näyttää toimivan ajettaessa ihan niinkuin kuuluu.

Koodi laadullisesti näyttää myös ihan hyvältä, vaikkakin koodia voisi kommentoida mielestäni lisää, ei niinkään vain arvioijan takia vaan myös lähinnä esim merkitsisi esim. missä kohtaa konkreettisesti tehdään mitäkin. Voi auttaa debuggaamista jos pitää omaa koodia vertailla pseudo-koodiin tai vastaavaan. (Kuten oletkin jo tehnyt esim. Primin algon toteutuksessa). 

Tietenkin myös metodien pienentäminen sitä myötä kun se on mahdollista voisi helpottaa toteutusta/luettavuutta, mutta toisaalta se voi olla vaikee tai mahdotonta tälläisissä algoritmeissa tai jopa turhaa työtä jos se vaikeuttaa vertailua dokumentaatioon, pseudo-koodiin yms. Lähinnä tuli mieleen että voisiko Boruvkan tapauksessa pilkkoa pienempiin kokonaisuuksiin?

Myös jatkoa ajatellen, mahdollisesti toteuttamalla solmulle metodin joka itsessään testaa onko jokin kaari kytköksissä siihen voisi välttyä EdgeHeap luokan contains metodin kaltaisilta melko rumilta toteuksilta. Muutenkin mielestäni kaikki mahdollinen vertailu ja kuuluvuus-suhteet yms. kannattaa hoitaa aina tälläisten rakenteiden sisäisesti mikäli se vain on mahdollista.

En löydä projektista näin silmämääräisesti + pikateustauksella bugeja tai muita varsinaisia virheitä, joten kokonaisuutena varsin hyvä suoritus!

Ladattu 22.2 2100

**Comment by rpulkka** [comment]
Kiitos palautteesta!

Olet oikeassa, että Boruvka luokkaa pitäisi siistiä, esim. pilkkomalla sitä pienemmiksi metodeiksi. Olet myös oikeassa siitä, että kommentointi on toistaiseksi puutteellista ja että kommentointi tulisi lisätä jo koodia kirjoittaessa, koska jälkikäteen on työlästä huomata mitä mikäkin rivi tekee. Sama ongelma on ollut myös testauksessa, minun olisi pitänyt testata ohjelmaa hieman varhaisemmassa vaiheessa kuin tein tässä projektissa, mutta onneksi testit olivat jo melko hyvät hetkellä, jolloin latasit projektin. 

Tsemppiä myös sinulle kurssin loppuun!
